package com.aurora.souschef;

import android.support.v7.app.AppCompatActivity;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentPagerAdapter;
import android.support.v4.view.ViewPager;
import android.os.Bundle;
import android.view.Gravity;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;

public class StepsActivity extends AppCompatActivity {
    private static final int TIMER_MARGIN = 10;


    /**
     * The {@link android.support.v4.view.PagerAdapter} that will provide
     * fragments for each of the sections. We use a
     * {@link FragmentPagerAdapter} derivative, which will keep every
     * loaded fragment in memory. If this becomes too memory intensive, it
     * may be best to switch to a
     * {@link android.support.v4.app.FragmentStatePagerAdapter}.
     */
    private SectionsPagerAdapter mSectionsPagerAdapter;

    /**
     * The {@link ViewPager} that will host the section contents.
     */
    private ViewPager mViewPager;

    private static final String[] DUMMY_STEPS = {
            "Take the food out of the package",
            "Put the food in the microwave",
            "Serve the hot food on a plate",
            "Enjoy your meal!"
    };

    private static final int[] DUMMY_TIMER_LOWER = {
            60,
            180,
            30,
            3600
    };

    private static final int[] DUMMY_TIMER_UPPER = {
            120,
            200,
            45,
            4000
    };

    public StepsActivity() {
        // default constructor
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_steps);

        // Create the adapter that will return a fragment for each of the three
        // primary sections of the activity.
        mSectionsPagerAdapter = new SectionsPagerAdapter(getSupportFragmentManager());

        // Set up the ViewPager with the sections adapter.
        mViewPager = (ViewPager) findViewById(R.id.container);
        mViewPager.setAdapter(mSectionsPagerAdapter);
        // Prevent ViewPager from resetting timers
        mViewPager.setOffscreenPageLimit(mSectionsPagerAdapter.getCount());

        // TODO: Add input from SouschefProc and delete DUMMY values
    }

    /**
     * A placeholder fragment containing a simple view.
     */
    public static class PlaceholderFragment extends Fragment {
        /**
         * The fragment argument representing the section number for this
         * fragment.
         */
        private static final String ARG_SECTION_NUMBER = "section_number";

        public PlaceholderFragment() {
            // Empty constructor (generated by Android Studio)
        }

        /**
         * Returns a new instance of this fragment for the given section
         * number.
         */
        public static PlaceholderFragment newInstance(int sectionNumber) {
            PlaceholderFragment fragment = new PlaceholderFragment();
            Bundle args = new Bundle();
            args.putInt(ARG_SECTION_NUMBER, sectionNumber);
            fragment.setArguments(args);
            return fragment;
        }

        @Override
        public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
            int index = getArguments().getInt(ARG_SECTION_NUMBER);

            // Inflate the CardView
            View rootView = inflater.inflate(R.layout.fragment_steps, container, false);

            // Set the TextViews
            TextView titleTextView = (TextView) rootView.findViewById(R.id.section_label);
            TextView stepTextView = (TextView) rootView.findViewById(R.id.tv_detail);
            titleTextView.setText(getString(R.string.section_format, index + 1));
            stepTextView.setText(DUMMY_STEPS[index]);

            // Inflate and save the Timers
            // TODO: Add loop for more timers
            View timerView = inflater.inflate(R.layout.timer_card, null);

            // Create the UITimer, which handles all the clicks by himself
            UITimer uiTimer = new UITimer(DUMMY_TIMER_LOWER[index],
                    DUMMY_TIMER_UPPER[index], timerView.findViewById(R.id.tv_timer));
            uiTimer.setOnClickListeners();

            // Set the right layoutparams for the timerView
            LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(
                    ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
            layoutParams.gravity = Gravity.CENTER;
            layoutParams.setMargins(0, TIMER_MARGIN, 0, TIMER_MARGIN);

            // Add the timerView to the LinearLayout
            ViewGroup insertPoint = (ViewGroup) rootView.findViewById(R.id.ll_step);
            insertPoint.addView(timerView, insertPoint.getChildCount(), layoutParams);

            return rootView;
        }
    }

    /**
     * A {@link FragmentPagerAdapter} that returns a fragment corresponding to
     * one of the sections/tabs/pages.
     */
    public class SectionsPagerAdapter extends FragmentPagerAdapter {

        public SectionsPagerAdapter(FragmentManager fm) {
            super(fm);
        }

        @Override
        public Fragment getItem(int position) {
            // getItem is called to instantiate the fragment for the given page.
            // Return a PlaceholderFragment (defined as a static inner class below).
            return PlaceholderFragment.newInstance(position);
        }

        @Override
        public int getCount() {
            // Return total pages.
            return DUMMY_STEPS.length;
        }
    }
}
