package com.aurora.souschef;

import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentPagerAdapter;
import android.support.v4.content.ContextCompat;
import android.support.v4.view.ViewPager;
import android.view.Gravity;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;

/**
 * Class defining the functionality of the recipe steps tab.
 */
public class Tab3Steps extends Fragment {
    private static final int TIMER_MARGIN = 10;
    private static final int INDICATOR_DOT_MARGIN = 3;

    private static final String[] DUMMY_STEPS = {
            "Take the food out of the package",
            "Put the food in the microwave",
            "Serve the hot food on a plate",
            "Enjoy your meal!"
    };

    private static final int[] DUMMY_TIMER_LOWER = {
            60,
            180,
            30,
            3600
    };

    private static final int[] DUMMY_TIMER_UPPER = {
            120,
            200,
            45,
            4000
    };

    private StepsPagerAdapter mStepsPagerAdapter;
    private ViewPager mViewPager;

    public Tab3Steps() {
        // Default constructor
    }

    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.tab_3_steps, container, false);

        // Create the adapter that will return a fragment for each of the three
        // primary sections of the activity.
        mStepsPagerAdapter = new StepsPagerAdapter(getActivity().getSupportFragmentManager());

        // Set up the ViewPager with the sections adapter.
        mViewPager = (ViewPager) rootView.findViewById(R.id.vp_steps);
        mViewPager.setAdapter(mStepsPagerAdapter);
        // Prevent ViewPager from resetting timers
        mViewPager.setOffscreenPageLimit(mStepsPagerAdapter.getCount());

        return rootView;
    }


    /**
     * A placeholder fragment containing the view of a step of the recipe
     */
    public static class PlaceholderFragment extends Fragment {
        /**
         * The fragment argument representing the section number for this
         * fragment.
         */
        private static final String ARG_SECTION_NUMBER = "section_number";
        private int mAmountSteps = 0;

        public PlaceholderFragment() {
            // Empty constructor (generated by Android Studio)
        }

        /**
         * Returns a new instance of this fragment for the given section
         * number.
         */
        public static PlaceholderFragment newInstance(int sectionNumber, int amountSteps) {
            PlaceholderFragment fragment = new PlaceholderFragment();
            fragment.mAmountSteps = amountSteps;
            Bundle args = new Bundle();
            args.putInt(ARG_SECTION_NUMBER, sectionNumber);
            fragment.setArguments(args);
            return fragment;
        }

        @Override
        public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
            int index = getArguments().getInt(ARG_SECTION_NUMBER);

            // Inflate the CardView
            View rootView = inflater.inflate(R.layout.fragment_steps, container, false);

            // Set the TextViews
            TextView titleTextView = (TextView) rootView.findViewById(R.id.tv_step_title);
            TextView stepTextView = (TextView) rootView.findViewById(R.id.tv_step_detail);
            titleTextView.setText(getString(R.string.section_format, index + 1));
            stepTextView.setText(DUMMY_STEPS[index]);

            // Inflate and save the Timers
            // TODO: Add loop for more timers
            View timerView = inflater.inflate(R.layout.timer_card, null);

            // Create the UITimer, which handles all the clicks by himself
            UITimer uiTimer = new UITimer(DUMMY_TIMER_LOWER[index],
                    DUMMY_TIMER_UPPER[index], timerView.findViewById(R.id.tv_timer));
            uiTimer.setOnClickListeners();

            // Set the right layoutparams for the timerView
            LinearLayout.LayoutParams layoutParamsTimer = new LinearLayout.LayoutParams(
                    ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
            layoutParamsTimer.gravity = Gravity.CENTER;
            layoutParamsTimer.setMargins(0, TIMER_MARGIN, 0, TIMER_MARGIN);

            // Add the timerView to the LinearLayout
            ViewGroup insertPoint = (ViewGroup) rootView.findViewById(R.id.ll_step);
            insertPoint.addView(timerView, insertPoint.getChildCount(), layoutParamsTimer);

            // Add the ImageViews to the LinearLayout for the indicator dots
            LinearLayout linearLayout = (LinearLayout) rootView.findViewById(R.id.ll_dots);
            ImageView tempView;
            LinearLayout.LayoutParams layoutParamsDot = new LinearLayout.LayoutParams(
                    ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
            layoutParamsDot.setMargins(INDICATOR_DOT_MARGIN, INDICATOR_DOT_MARGIN,
                    INDICATOR_DOT_MARGIN, INDICATOR_DOT_MARGIN);

            // For every step, add a dot and make sur the right one is selected
            for (int i = 0; i < mAmountSteps; i++) {
                tempView = (ImageView) inflater.inflate(R.layout.dot_image_view, null);
                if (i == index) {
                    tempView.setBackground(ContextCompat.getDrawable(getContext(), R.drawable.selected_dot));
                } else {
                    tempView.setBackground(ContextCompat.getDrawable(getContext(), R.drawable.not_selected_dot));
                }
                tempView.setLayoutParams(layoutParamsDot);
                linearLayout.addView(tempView);
            }

            return rootView;
        }
    }

    /**
     * A {@link FragmentPagerAdapter} that returns a fragment corresponding to
     * one of the sections/tabs/pages.
     */
    public class StepsPagerAdapter extends FragmentPagerAdapter {

        public StepsPagerAdapter(FragmentManager fm) {
            super(fm);
        }

        @Override
        public Fragment getItem(int position) {
            // getItem is called to instantiate the fragment for the given page.
            // Return a PlaceholderFragment (defined as a static inner class below).
            return PlaceholderFragment.newInstance(position, getCount());
        }

        @Override
        public int getCount() {
            // Return total pages.
            return DUMMY_STEPS.length;
        }
    }
}
